### ISSUE TITLE
Design Verification of Multiple File Input Control Option in Multi Download 

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#12]
Please refer this screenshot: https://nimb.ws/QWypLi

It should be like this: https://nimb.ws/L9AjOK
Please refer specs for more details.

**Comment by Myresearchergit** [comment]
These are done:-
1)  Remove bold from text
2). Text changed to lowercase 
3). Remove  border
4). Button disable conditions

**Comment by SakshiArora27** [comment]
Please refer this screenshot: https://nimb.ws/pWhMCx
Due to some changes WP default Input file control option design is breaking. Please check
https://nimb.ws/83QYUu

**Comment by Myresearchergit** [comment]
Fixed as mention in screenshot

**Comment by SakshiArora27** [comment]
Still not fixed. Please refer this: https://nimb.ws/ln089O
It should be like this: https://nimb.ws/QWypLi

**Comment by SakshiArora27** [comment]
In firefox Browse button is not appearing properly. Also, Install Now button should be aligned with browse button. Please refer this: 

![firefox](https://user-images.githubusercontent.com/33451850/62347662-0f2d9980-b518-11e9-8ce8-be34e8ec8db3.png)

It should be like this: 

![ff-wp](https://user-images.githubusercontent.com/33451850/62347701-31bfb280-b518-11e9-96c7-e1cf242ef5e6.png)

**Comment by Myresearchergit** [comment]
Now Multiple upload section same as default, please check

**Comment by SakshiArora27** [comment]
Please see screenshot: https://nimb.ws/WLz4mK
Also, Firefox issue is not resolved. Please check my comment above regarding this.

**Comment by Myresearchergit** [comment]
Please check now.  We make a little bit change.

**Comment by SakshiArora27** [comment]
Now, No file chosen text is missing between the 2 buttons. Also drag and drop plugin functionality is not working. See screenshot: https://nimb.ws/m5leOH

Please make it same as default WP.
Refer this: https://nimb.ws/d0o3gQ
In Firefox also make it same as WP default.
